// can use to test API calls with REST Client extension on VSCode
GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Mallow",
    "password": "password"
}